### ISSUE TITLE
3.2中求部门中所有人薪水的平均等级有问题

### ISSUE THREAD

**Issue by westmelon** [guoxiaoxu/Guo-MySQL-Practice-Questions#1]
应该是这样吧?:
`select t.deptno,avg(t.grade) as avggrade from
(select
  e.ename,e.sal,e.deptno,s.grade
from
  emp e
join
  salgrade s
on
  e.sal between s.losal and s.hisal ) t group by t.deptno`

**Comment by guoxiaoxu** [comment]
谢谢你指出错误，忘加avg()函数了。你试下下面这种方法，在第一步的基础上直接按deptno分组。
select
  e.deptno,avg(s.grade)
from
  emp e
join
  salgrade s
on
  e.sal between s.losal and s.hisal
group by
  e.deptno;
